Add weeks to catalan locale
arrow-py/arrow pull request #1189
Opened 2024-09-30 03:20 UTC by rimu

- [ ] 🧪  Added **tests** for changed code.
- [ ] 🛠️  All tests **pass** when run locally (run `tox` or `make test` to find out!).
- [ ] 🧹  All linting checks **pass** when run locally (run `tox -e lint` or `make lint` to find out!).
- [ ] 📚  Updated **documentation** for changed code.
- [x] ⏩  Code is **up-to-date** with the `master` branch.

## Description of Changes

Hopefully a trivial change that doesn't require tests, etc

2024-09-30 04:52 UTC, krisfremen requested changes
Thanks for your contribution to arrow @rimu

Can you add some tests for this?

Cheers!

2024-10-19 14:54 UTC, jadchaar commented
@rimu would it be possible to add some unit tests? Then we can merge this in.

2024-10-19 23:13 UTC, rimu commented
No sorry, I don't think it's worth it for such a trivial change.

2024-10-24 05:44 UTC, jadchaar approved these changes

2024-10-24 05:45 UTC, merged