Bump version to 1.0.0 and update CHANGELOG
arrow-py/arrow pull request #924
Opened 2021-02-23 21:10 UTC by systemcatch

## Pull Request Checklist

Thank you for taking the time to improve Arrow! Before submitting your pull request, please check all *appropriate* boxes:

- [ ] 🧪  Added **tests** for changed code.
- [ ] 🛠️  All tests **pass** when run locally (run `tox` or `make test` to find out!).
- [ ] 🧹  All linting checks **pass** when run locally (run `tox -e lint` or `make lint` to find out!).
- [ ] 📚  Updated **documentation** for changed code.
- [ ] ⏩  Code is **up-to-date** with the `master` branch.

If you have *any* questions about your code changes or any of the points above, please submit your questions along with the pull request and we will try our best to help!

## Description of Changes

Still a WIP

2021-02-23 21:38 UTC, krisfremen approved these changes
It's finally happening! Looks good to me.

🚀🎉🎉🎉

2021-02-23 21:42 UTC, krisfremen approved these changes
Tiny nitpick from my side.

2021-02-23 21:42 UTC, krisfremen commented on CHANGELOG.rst
> +    (<Arrow [2013-05-05T12:30:00+00:00]>, <Arrow [2013-05-05T13:29:59.999999+00:00]>)
Tiny nitpick, but maybe we can update the old years to current year?

Keep up with the times 😉

2021-02-23 21:47 UTC, jadchaar requested changes
Few comments!

2021-02-23 21:47 UTC, jadchaar commented on CHANGELOG.rst
> +- [INTERNAL] Added type annotations throughout the codebase.
I think this should be under [NEW] since it is a huge change. Like `[NEW] Arrow now natively supports PEP 484-style type annotations.`

2021-02-23 21:47 UTC, jadchaar commented on CHANGELOG.rst
> +1.0.0 (2021-02-xx)
Should preface the bullets with a sentence like "After 8 years, we are finally pleased to announce Arrow v1.0. Thanks to the entire Python community for helping to make Arrow the amazing package it is today!

2021-02-23 21:47 UTC, jadchaar commented on CHANGELOG.rst
> +- [CHANGE] Arrow has **dropped support** for Python 2.7 and 3.5.
Maybe add a CHANGE bullet saying that Arrow is now following semantic versioning (https://semver.org/)?

2021-02-23 21:47 UTC, jadchaar commented on arrow/_version.py
> +__version__ = "1.0.0"
Wow that feels good!

2021-02-24 11:29 UTC, systemcatch commented
Hey guys I will make the suggested changes then get this ready for review. Do you think we should just link to the migration guide for breaking changes or do they need to be in the changelog as well?

2021-02-24 19:27 UTC, jadchaar commented
> Hey guys I will make the suggested changes then get this ready for review. Do you think we should just link to the migration guide for breaking changes or do they need to be in the changelog as well?

I think just linking an being explicit about the migration guide outlining the breaking changes is sufficient.

2021-02-24 22:09 UTC, jadchaar approved these changes
LGTM. Ship it! 🚀🚀🚀🚀🚀🚀

2021-02-24 22:23 UTC, krisfremen commented
Let's ship it! 💎 🚀 🚀 🚀 🚀 

Feeling excited!

2021-02-25 10:58 UTC, merged

2021-02-26 10:18 UTC, michael-k commented
There's no tag on GitHub and no release on PyPI.  Is this on purpose?  Just wondering :)

2021-02-26 10:56 UTC, systemcatch commented
> 
> 
> There's no tag on GitHub and no release on PyPI. Is this on purpose? Just wondering :)

Haha no, one of us needs to push the button to publish. Should be coming today when I finish work.

2021-02-26 14:00 UTC, systemcatch commented
@michael-k and it's released! :partying_face: